### ISSUE TITLE
Have a -dryrun option

### ISSUE THREAD

**Issue by tngraf** [sw360/capycli#38]
To be discussed: do we need tom kind of `-dryrun` option for all commands that write to SW360?  
Would this prevent unexperienced users from creating large numbers of moderation requests?

**Comment by gernot-h** [comment]
We already discussed this in our old, Siemens-internal issues 47 and 161.

I think there are different reasons for many moderation requests:

- User doesn't understand implications of feeding large BOMs into SW360 and thus creates lot of unnecessary components and/or releases
- User doesn't strive to avoid duplicates and thus creates lot of duplicate components and/or releases
- User has incomplete BOM triggering wrong updates in SW360
- CaPyCli triggers unnecessary changes e.g. when updating releases

So the major question is whether the performed changes are valid and necessary. If yes, then it's the moderation request feature itself which should be fixed in SW360. ;) If not, the question is whether we should improve CaPyCli to detect unnecessary changes (e.g. not update existing URLs etc.)  or how we could "educate" users by additional print()s. 

I think adding --dryrun alone would only help if we add helpful tracing messages which tell the user exactly when CaPyCli would update specific attributes of an existing object or when it would create a new one.

And it would also be very helpful to inform then user when a moderation request is triggered, but I think that's nothing the API will tell us, right?

On the other hand, I did some trial and error in the past (usually using BOMs with one or few item(s) and manually undoing unwanted changes) such a feature might have been helpful.

**Comment by gernot-h** [comment]
There's one more aspect: telling the user that we would create moderation requests might also lead to users trying to circumvent this by deliberately creating "their own" components or releases in SW360. Not sure if we want to foster this. ;)

**Comment by nzupan** [comment]
Many valid points have already been stated. I would just add that from the perspective of minimizing unnecessary moderation requests, this would be a great addition. When feeding in large BOMs it is a challenge to know the amount of moderation requests that capycli will create. This would help finding cases when capycli generates unnecessary changes or spot potential bugs.
